### PR TITLE
rich text in dashboard

### PR DESCRIPTION
**Pull request by testing-life**
## What was done
image

#### After

### CODE REVIEW

**Review by hiaux0 — CHANGES_REQUESTED** [review]
for: https://prime-deals-dapp-git-feature-1150-rich-text-in-18087c-curvelabs.vercel.app/deal/5fVjBaQc36MxuMGqSzizTG

clauses empty

(and discussions still has html)

image

**Comment by testing-life** [comment]
ah sorry, left a test var in there :/

**Review by hiaux0 — CHANGES_REQUESTED** [review]
discussion misses somes styles it seems

image

**Comment by testing-life** [comment]
ok, i've tried including everyting, with the clause title

**Review by hiaux0 — COMMENTED** [review]
- clause title missing in submit -> terms ([figma](https://www.figma.com/file/hTLvqCEzki3WoG5uJbtynw/Prime-Deals?node-id=11498%3A166982))

- styles for dashboard - Deal clauses
    - title is off
    - background?

image
([figma](https://www.figma.com/file/hTLvqCEzki3WoG5uJbtynw/Prime-Deals?node-id=11975%3A179663))

**Review by hiaux0 — APPROVED** [review]
:green_apple: 

sry for requesting stuff outside of the PR. Will try to take more care!

**Pull request merged**
