### PR TITLE
chore(eslint): fix tsconfig in other dirs (other than /src)

### PR DESCRIPTION
**Pull request by hiaux0**
## What was done
- wrong tsconfig <> eslint configurations (aurelia-cli also has this wrong I just checked)
- Fix by changing to (basically try to include the tsconfig.json inside /cypress)
```diff
- eslint.json
+ eslint.cjs
```

## Testing
- Open any .ts file inside /cypress

#### Before
image

#### After
eslint gets picked up inside /cypress
image

### CODE REVIEW

**Comment by hiaux0** [comment]
Weird though, that the lint CI task did not trigger anything 🤔 
I'd leave it for another PR, because we have to relint /cypress anyway.
Also like to do it later after all the parallel work on Stage + corresponding cypress changes is in `development`

**Review by dkent600 — CHANGES_REQUESTED** [review]
Does `npm run lint` still work?  Does eslint still run in vscode on file save?

**Comment by hiaux0** [comment]
> npm run lint

`development` and this branch yield the same result:
image

> eslint on save in vscode
yes

@dkent600 Can you also verify this please?

**Comment by hiaux0** [comment]
> Weird though, that the lint CI task did not trigger anything 🤔

Because /cypress is not in the `lint` script
#136

**Comment by dkent600** [comment]
> 

confirmed

**Comment by dkent600** [comment]
> @dkent600 Can you also verify this please?

confirmed

**Review by dkent600 — APPROVED** [review]

**Pull request merged**
