### PR TITLE
Made the home page mobile responsive

### PR DESCRIPTION
**Pull request by IonelLupu**
## What was done
Mock: https://www.figma.com/file/hTLvqCEzki3WoG5uJbtynw/Prime-Deals?node-id=7557%3A116288
image

#### After

### CODE REVIEW

**Comment by hiaux0** [comment]
**! Note !
Code looks straightforward.
Fnality: I started to compare with mocks (see below), but realized, we don't have to go pixel perfect, so all of that below is just optional.**

---
---

### Wallet menu right margin
image

### Navbar margin
image

### View all Deals left margin
image

### View all Deals margin bottom
image

**Comment by IonelLupu** [comment]
@hiaux0  Updated the design. Please take a look again. 

These is still one weird issues about the left-right spacing of the entire app (your "View all Deals left margin" image) which shows pretty much correctly on my side:
image


It seems that on your browser the space is way smaller. I will have to inspect that

**Comment by hiaux0** [comment]
> It seems that on your browser the space is way smaller. I will have to inspect that

Don't worry I'd say. Somehow my browser has weird glitches all around the place.

**Review by dkent600 — CHANGES_REQUESTED** [review]
1) I don't think these cards should be single-column at this breakpoint around 1000px:

image

2) Tabs should have greater margins at this point (more centered):

image

**Review by dkent600 — CHANGES_REQUESTED** [review]
Changes per our discussion today

**Review by dkent600 — APPROVED** [review]

**Pull request merged**
