### PR TITLE
swapped order of deal info dao name labels

### PR DESCRIPTION
**Pull request by IonelLupu**
## What was done
image
image

#### After

### CODE REVIEW

**Review by dkent600 — CHANGES_REQUESTED** [review]
1) can you please supply screenshots of the changes, thanks
2) the label should not wrap unless necessary:

image

**Review by dkent600 — CHANGES_REQUESTED** [review]
Can you please include a screenshot of what it looks like when there are a lot of social media links?

**Comment by IonelLupu** [comment]
@dkent600  added another screenshot. Unfortunately, I had to add a hack to make it fit up to 9 external links. Without the hack (you will see the ternary operator in HTML) it can fit only 7 external links. Not sure why do we have to support this many in the UI, because the registration wizard has a hard condition for up to 5 external links.

**Comment by dkent600** [comment]
If there if is a limit of 5 then 5 is all we need support From: Ionel lupu ***@***.***>Sent: Sunday, April 17, 2022 2:17 PMTo: PrimeDAO/prime-deals-dapp ***@***.***>Cc: Doug Kent ***@***.***>; Mention ***@***.***>Subject: Re: [PrimeDAO/prime-deals-dapp] swapped order of deal info dao name labels (PR #681) 
@dkent600  added another screenshot. Unfortunately, I had to add a hack to make it fit up to 9 external links. Without the hack (you will see the ternary operator in HTML) it can fit only 7 external links. Not sure why do we have to support this many in the UI, because the registration wizard has a hard condition for up to 5 external links.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
Get Outlook for iOS

**Review by dkent600 — APPROVED** [review]

**Pull request merged**
