### PR TITLE
chore(docs): add PR template

### PR DESCRIPTION
**Pull request by hiaux0**
Suggestion to add a template to _all_ PRs.
Note: one can specify multiple PR templates [github docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository), but usage is kind of unpractical, because one would need to add a query to the url.

Usage in PR: https://github.com/PrimeDAO/prime-launch-dapp/pull/705

image

### CODE REVIEW

**Comment by IonelLupu** [comment]
@hiaux0  what's the "Testing before/after" about? From your example looks like it's the before and after of the UI

**Comment by hiaux0** [comment]
> @hiaux0 what's the "Testing before/after" about? From your example looks like it's the before and after of the UI

@IonelLupu 

At least for me, when I review a PR, I'd like to verify the "bug" or "old/before" behavior.
Having it written in a text form is helpful.
One can also just simply link to an issue (if bug fix).
One can also leave out "Testing" in general".

Use cases
1. UI
2. Any bug fix
- Chore/Internal: "Before: cypress command saved videos" --> "After: does not save videos"
- Refactoring: "Before: serviceA and serviceB" --> "After: merged into new serviceC"

**Review by paweljanicki — APPROVED** [review]

**Review by giladt — COMMENTED** [review]
I find it practical with small PRs / Bug fixes / UI twicks. How do you see this template working with bigger PRs, like for example the Discussion feature, which includes much more moving parts. How detailed should it be in this case?

**Comment by hiaux0** [comment]
>  How do you see this template working with bigger PRs

At least the "What was done" section still applicable imo.
We may have to manually add other sections though (like here: https://github.com/PrimeDAO/prime-deals-dapp/pull/63)

Generally, for now, I'd suggest to observe other possible templates, and see if we want to create more templates

**Review by dkent600 — APPROVED** [review]

**Pull request merged**
