### PR TITLE
784- Replies Column display the total amount of comments happened while deal was private.

### PR DESCRIPTION
**Pull request by giladt**
## What was done
Split replies count in `clauseDiscussion` into:
 - replies: total count of public and private comments
 - publicReplies: count of only public comments (metadata.isPrivate === "false")

The discussions list shows the replies count based on the deal authentication state:
If a user is authenticated as a representative/proposal lead- will show the `replies` count, otherwise the `publicReplies`.

### CODE REVIEW

**Review by hiaux0 — CHANGES_REQUESTED** [review]
## code
- looks good overall
- missed one place: 
`if.to-view="!discussionsService.discussions[clause.id] || discussionsService.discussions[clause.id].replies === 0">Begin A Discussion</div>`
Would it be enough to use ?:
```diff
- discussions[clause.id].replies
+ discussions[clause.id].publicReplies
```

## Fnaclity
- generally works
- works when disconnecting
- :warning: not working for changing accounts (or reconnecting to address, that can see private comment)


video

**Review by dkent600 — APPROVED** [review]

**Comment by giladt** [comment]
> missed one place in dealClauses.html

- If it's an open deal- all threads are public, so 'replies' and 'publicReplies' should always be the same since the deal can not be private.
- If it's a partnered deal- only representatives/proposal lead can discuss, thus by definition see private discussions (if connected). so 'replies' is correct and shows the total count of public+private comments.
- If no user is not connected, then the `discuss`/`begin a discussion` button is not visible.

**Comment by giladt** [comment]
> * ⚠️ not working for changing accounts (or reconnecting to address, that can see private comment)

Will be handled in a separate issue / PR: #918

**Review by hiaux0 — APPROVED** [review]
> If it's a partnered deal- only representatives/proposal lead can discuss, thus by definition see private discussions (if connected). so 'replies' is correct and shows the total count of public+private comments.

Makes sense :heavy_check_mark:

**Pull request merged**
